In [1]:
dict_code_prof = {
    'V0601':{'sexo':{'1':'Masculino','2':'Feminino'}},
    'V0606':{'cor':{'1':'Branca','2':'Preta','3':'Amarela','4':'Parda','5':'Indigena','9':'Sem_declaracao'}},
    'V6400':{'nivel_de_instrucao':{'1':'Sem_instrucao','2':'fundamental_completo','3':'medio_completo','4':'superior_completo'}},
    'V0640':{'estado_civil':{'1':'casado','5':'solteiro','4':'viuvo','3':'divorciado','2':'desquitado'}},
    'V0645':{'trabalho':{'1':'um','2':'dois_ou_mais','':'nenhum'}},
    'V6526':'renda_em_salarios_minimos',
    'V0653':'horas_trabalhadas',
    'V0662':{'tempo_de_deslocamento_ao_trabalho':{'1':'<=5min','2':'6-30min','3':'31min-1h','4':'1-2h','5':'>2h'}},
    'V6940':{'categoria_profissional':{'1':'empregado_clt','2':'empregado_estatuario(militares_inclusos)','3':'empregado_sem_clt','4':'conta_propria','5':'empregador','6':'nao_remunerado','7':'trabalhador_subsistente'}},
    'V5080':'rendimento_familiar_per_capita_em_salarios_minimos',
    'V1005':{'situacao_do_setor':{'1':'area_urbanizada','2':'area_nao_urbanizada','3':'area_urbanizada_isolada','4':'area_rural_de_extensao_urbana','5':'aglomerado_rural','6':'aglomerado_rural','7':'aglomerado_rural','8':'area_rural_exclusive_aglomerado_rural'}},
    'V0221':{'motocicleta_para_uso_particular':{'1':'possui','2':'nao_possui'}},
    'V0222':{'automovel_para_uso_particular':{'1':'possui','2':'nao_possui'}},
}

In [27]:
import pandas as pd

def read_ibge_microdata(txt_path, layout_path, sheet_name='PESS'):
    # Read layout sheet
    layout = pd.read_excel(layout_path, sheet_name=sheet_name, engine='odf').iloc[1:]
    
    # Extract variable names and positions
    var_names = layout.iloc[:, 0].astype(str).tolist()
    starts = layout.iloc[:, 7].astype(float).astype(int).tolist()
    ends = layout.iloc[:, 8].astype(float).astype(int).tolist()
    
    # Build colspecs
    colspecs = [(start - 1, end) for start, end in zip(starts, ends)]
    
    # Read fixed-width file
    df = pd.read_fwf(txt_path, colspecs=colspecs, names=var_names)
    
    return df

txt_path = '.\\data\\Amostra_Pessoas_14munic.txt'
layout_path = '.\\Layout_microdados_Amostra.ods'

df = read_ibge_microdata(txt_path, layout_path)

In [30]:
df

,V0001,V0002,V0011,V0300,V0010,V1001,V1002,V1003,V1004,V1006,...,M6693,M0670,M0671,M6800,M6121,M0604,M0605,M6462,M6472,V1005
0,21,5302,2105302006001,3703,158089220776258,2,2,9,5,1,...,2,2,2,2,2,2,2,1,2,1
1,21,5302,2105302006001,3703,158089220776258,2,2,9,5,1,...,2,2,2,2,2,2,2,2,2,1
2,21,5302,2105302006001,3703,158089220776258,2,2,9,5,1,...,2,2,2,2,2,2,2,2,2,1
3,21,5302,2105302006001,3703,158089220776258,2,2,9,5,1,...,2,2,2,2,2,2,2,2,2,1
4,21,5302,2105302006001,3703,158089220776258,2,2,9,5,1,...,2,2,2,2,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841829,43,23002,4323002006013,6139713,110876425836419,4,5,26,34,1,...,2,2,2,2,2,2,2,2,2,2
841830,43,23002,4323002006013,6139713,110876425836419,4,5,26,34,1,...,2,2,2,2,2,2,2,2,2,2
841831,43,23002,4323002006013,6161988,105318642192176,4,5,26,34,2,...,2,2,2,2,2,2,2,2,2,8
841832,43,23002,4323002006013,6161988,105318642192176,4,5,26,34,2,...,2,2,2,2,2,2,2,2,2,8
841833,43,23002,4323002006013,6163362,143524268587654,4,5,26,34,2,...,2,2,2,2,2,2,2,2,2,8

In [4]:
import geopandas as gpd
GDF_saopaulo = gpd.read_file('C:\\Users\\João Rahal\\Desktop\\estagio\\bike-science\\sao-paulo\\bike-infra-maps\\code\\dados\\sao_paulo_demographics.geojson')


mask = df['V0011'].astype(str).apply(
    lambda num: GDF_saopaulo['setor_cens'].str.contains(num, na=False).any()
)

commons = df[mask].copy()
commons

KeyboardInterrupt: